---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Appserver-VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      
    Appserver-Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref  Appserver-VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
      
    Appserver-SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Security Group for Game Servers"
      VpcId: !Ref  Appserver-VPC
      
    Appserver:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ff8a91507f77f867
      KeyName: MyKeyPair
      SecurityGroupIds:
      - !Ref  Appserver-SecurityGroup
      SubnetId: !Ref  Appserver-Subnet
    Appserver-ELB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Subnets:
      - !Ref  Appserver-Subnet
      
   Webserver-TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthyThresholdCount: 3
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 3
      VpcId: !Ref  Appserver-VPC
      
   Appserver-Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref  Appserver-TargetGroup
      LoadBalancerArn: !Ref  Appserver-ELB
      Port: 80
      Protocol: HTTP
      
  Appserver-EFS:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      FileSystemTags:
        - Key: Name
          Value:  Appserver-EFS
      PerformanceMode: maxIO
      
  Appserver-EBS:
    Type: 'AWS::EBS::Volume'
    Properties:
      Size: 20
      AvailabilityZone: us-east-1a
      
  Appserver-DynamoDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
      - AttributeName: playerId
        AttributeType: S
      KeySchema:
      - AttributeName: playerId
        KeyType: HASH
-

